[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]  
clap = { version = "4.5.20", features = ["derive"] }
actix-web = "4"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
convert_case = "0.6.0"
